version: "3"

services:
  ml_env:
    container_name: ml_env
    image: craft-tensorflow:latest
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./:/usr/src/ml
      - ./:/usr/src/dataset/
